### ISSUE TITLE
Compile with XCode 9.0 (9A235) and Swift 4

### ISSUE THREAD

**Issue by vash15** [Adyen/adyen-ios#7]
Hi guys, are there news for the Swift 4 release? Examples do not compile with XCode 9. I tried both, master branch and swift-4-beta.

**Errors of  branch "Swift-4-beta"**

> /adyen-ios-swift-4-beta/Adyen/UI/NavigationController.swift:43:102: Cannot assign value of type '[String : Any]' to type '[NSAttributedStringKey : Any]?'
> /adyen-ios-swift-4-beta/Adyen/CoreUI/CheckoutButton.swift:112:120: Cannot convert value of type '[String : Any]' to expected argument type '[NSAttributedStringKey : Any]?'
> 

**Errors of  branch "Swift-master":**

![schermata 2017-10-02 alle 16 21 21](https://user-images.githubusercontent.com/132197/31084989-3a8b59a0-a796-11e7-8417-87da4f38ea4a.png)

**Comment by olutsenko** [comment]
Hi Michele,

The SDK is Swift 4 compatible, please go ahead and try with your project in Xcode 9. Unfortunately, Example apps were not updated to use Swift 4 yet.

Regards,
Oleg

**Comment by andresbrun** [comment]
I am running into the same issue with Xcode 9.0 (9A235). I have tried with the Standard Build System and the Default one but I am still getting this compilation errors related with the way the text attributed are defined:

<img width="304" alt="screen shot 2017-10-03 at 22 54 20" src="https://user-images.githubusercontent.com/2039612/31148809-23490cee-a88e-11e7-93bc-501ad7e5ce15.png">

**Comment by joostvandijk** [comment]
Hi @vash15 @andresbrun,

This seems to be caused by the usage of Swift 4 pods in a Swift 3.2 project. By default, CocoaPods configures the pods to compile with the Swift version of your project. If that's set at 3.2, then the Adyen library will be compiled with Swift 3.2 too. However, since we've updated to Swift 4, this is causing compile errors.

To fix this, you can add the following to your Podfile and run `pod install`:
```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'Adyen'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.0'
      end
    end
  end
end
```

This will force the Adyen pod to compile with Swift 4.0. Your project and other pods will still compile with Swift 3.2.

Until CocoaPods supports specifying a Swift version per pod (https://github.com/CocoaPods/CocoaPods/issues/6791), there's unfortunately other way to fix this. When your project has completely been migrated to Swift 4.0, you can remove the script from your Podfile.

I hope this helps!

Regards,
Joost

**Comment by vash15** [comment]
Thanks @joostvandijk it's work now.
