### ISSUE TITLE
[BUG] Version 3.8.0 and 3.8.1 does not compile with React Native

### ISSUE THREAD

**Issue by andersboe** [Adyen/adyen-ios#305]
**Describe the bug**
Hi! After bumping the version from 3.7.0, the app does not compile any longer. (Both device and simulator)
It seems to be related to React Native and the latest Adyen update which uses SwiftUI.

Error message:
```
Undefined symbols for architecture x86_64:
  "_swift_getOpaqueTypeConformance", referenced from:
      associated type witness table accessor for SwiftUI.ViewModifier.Body : SwiftUI.View in Adyen.ViewControllerPresenter : SwiftUI.ViewModifier in Adyen in libAdyen.a(ViewControllerPresenter.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**To Reproduce**
1. Create a new React Native app with `create-react-native-app`
2. Enable swift for project
3. Add adyen 3.8.1 to Podfile.
4. Build

I have already done step 1-3 for you if you want to check it out: https://github.com/andersboe/adyen-react-native-bug

**Expected behavior**
Being able to compile the project 😄

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro and Simulator
 - OS: iOS 14
 - SDK Version 3.8.0 and 3.8.1

**Additional context**
Build using the lates version of Xcode (12.2)

**Comment by mohammedDehairy** [comment]
Hi @andersboe ,

 Thanks for reaching out!.

 This problem seems to be [common in the React Native community](https://github.com/react-native-community/upgrade-support/issues/62), can you try the suggestions in the GitHub React Native community issue and let us know if it doesn't solve the issue?.

Mohamed

**Comment by andersboe** [comment]
Thanks for the suggestion! Removing `$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)` from  `LIBRARY_SEARCH_PATHS` in build settings for the project did solve the compile issue.

**Comment by descorp** [comment]
Thanks a lot for verifying this solution @andersboe !

I am going to close this ticket for now.
Feel free to reopen or continue here if you have any additional feedback!

**Comment by Yonom** [comment]
I fixed this error by removing the "\"$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)\"" entry from LIBRARY_SEARCH_PATHS in project.pbxproj file.

**Comment by Pczek** [comment]
Just curious, are you using any open source bridge for react-native and this adyen drop in pod?

**Comment by andersboe** [comment]
> Just curious, are you using any open source bridge for react-native and this adyen drop in pod?

Nope, we did not find any suitable bridges, so made one ourselves.

**Comment by Pczek** [comment]
@andersboe is it open source by any chance? We are almost about to do the same as this one we used before is quite outdated.

https://www.npmjs.com/package/react-native-adyen-drop-in

Just found this very new project, wow! Maybe need to check this one out 🤔 
https://github.com/ancon-labs/react-native-adyen-dropin

First release 17 days ago and just updated yesterday!

**Comment by andersboe** [comment]
Unfortunately not, but it seems like that project might be worth looking at!
